DISTRO = "emmc"

MACHINE = "udoo-bolt-emmc"

PREFERRED_PROVIDER_virtual/kernel = "emmc-linux"

KERNEL_PACKAGE_NAME = "emmc"
KERNEL_ARTIFACT_NAME = "${KERNEL_PACKAGE_NAME}-${MACHINE}"

TMPDIR .= "-${BB_CURRENT_MC}"
