DISTRO = "emmc"

MACHINE = "udoo-bolt-emmc"

PREFERRED_PROVIDER_virtual/kernel = "emmc-linux"

KERNEL_PACKAGE_NAME = "emmc-linux"
KERNEL_ARTIFACT_NAME = "emmc-${MACHINE}"

TMPDIR .= "-${BB_CURRENT_MC}"
