require conf/machine/v1000.conf

WKS_FILE ?= "liveusb.wks"

BOLT_ROOT_DEVICE ?= "/dev/ram0"

SERIAL_CONSOLES ?= "115200;ttyS0"

KERNEL_ARGS ?= "BOLT_BLOCK_DEVICE=${BOLT_BLOCK_DEVICE} console=tty1 console=ttyS0,115200n8 rootfstype=ext4"
