require conf/machine/v1000.conf

SERIAL_CONSOLES ?= "115200;ttyS0"

KERNEL_ARGS ?= "console=tty1 console=ttyS0,115200n8 rootwait rootfstype=ext4"

WKS_FILES = "emmc.wks"
WKS_SEARCH_PATH = "${BOLT_LAYERDIR}/recipes-emmc/images"
