DISTRO_NAME = "UDOO OS"
DISTRO_VERSION = "0.0.1"
DISTRO_CODENAME = "bolt"

MAINTAINER = "Underview <vince@underview.tech>"

TARGET_VENDOR = "-udoo"

LOCALCONF_VERSION = "2"

PREMIRRORS = "\
git://.*/.*   http://downloads.yoctoproject.org/mirror/sources/ \n \
gitsm://.*/.* http://downloads.yoctoproject.org/mirror/sources/ \n \
hg://.*/.*    http://downloads.yoctoproject.org/mirror/sources/ \n \
p4://.*/.*    http://downloads.yoctoproject.org/mirror/sources/ \n \
svn://.*/.*   http://downloads.yoctoproject.org/mirror/sources/ \n"

# QA check settings - a little stricter than the OE-Core defaults
WARN_TO_ERROR_QA = "already-stripped compile-host-path install-host-path \
                    installed-vs-shipped ldflags pn-overrides rpaths staticdev \
                    unknown-configure-option useless-rpaths"
WARN_QA:remove = "${WARN_TO_ERROR_QA}"
ERROR_QA:append = " ${WARN_TO_ERROR_QA}"

INHERIT += "uninative"

BB_SIGNATURE_HANDLER ?= "OEEquivHash"

BB_HASHSERVE ??= "auto"
BB_HASHSERVE_DB_DIR ??= "${SSTATE_DIR}"

DISTRO_FEATURES = ""
DISTRO_EXTRA_RDEPENDS += "packagegroup-core-boot"
DISTRO_VERSION[vardepsexclude] = "DATE"

require ./include/support-coreutils.inc
require ./include/support-systemd.inc
