require ./common.conf

WKS_FILES = "liveusb.wks"
WKS_SEARCH_PATH = "${BOLT_LAYERDIR}/recipes-liveusb/images"

PREFERRED_PROVIDER_virtual/kernel ?= "liveusb-console-linux"

#KERNEL_PACKAGE_NAME ?= "liveusb-console"
KERNEL_ARTIFACT_NAME ?= "liveusb-console-${MACHINE}"
